// Hand-written types mirroring supabase/migrations/*.sql.
//
// These are NOT generated by `supabase gen types` (no live project is
// linked yet). Once a real Supabase project exists, regenerate with:
//   supabase gen types typescript --project-id <ref> > src/types/database.ts
// and reconcile any drift against this file.
//
// IMPORTANT: every Row/Insert/Update shape below is declared with `type`,
// not `interface`. This is not a style choice — TypeScript's structural
// check for "does this satisfy Record<string, unknown>" (which
// supabase-js's GenericTable constraint relies on) treats `interface`
// declarations as NOT satisfying an index signature, even though a
// structurally identical `type` alias does. Using `interface` here
// silently collapses every table's Insert/Update/Row generics to `never`
// with no error pointing at the cause — see the PR description for the
// full diagnosis. Keep these as `type`.

export type ProfileRole = 'admin' | 'care_advocacy' | 'committee' | 'contractor' | 'specialist';
export type ClientStatus = 'active' | 'inactive';
export type ShiftStatus = 'scheduled' | 'completed' | 'cancelled';
export type TaskPriority = 'low' | 'medium' | 'high';
export type TaskStatus = 'todo' | 'in_progress' | 'done';
export type DocumentCategory =
  | 'care_plan'
  | 'bsp_risk_plan'
  | 'consent_form'
  | 'service_agreement'
  | 'policy'
  | 'correspondence'
  | 'other';
export type DocumentStatus = 'draft' | 'pending_approval' | 'approved';
export type TransactionType = 'income' | 'expense';
export type OnboardingStep =
  | 'wwcc'
  | 'ndis_screening'
  | 'orientation'
  | 'code_of_conduct'
  | 'referees'
  | 'induction';
export type IncidentDomain = 'ndis_reportable' | 'whs' | 'security' | 'other';
export type IncidentCategory =
  | 'death'
  | 'serious_injury'
  | 'abuse'
  | 'neglect'
  | 'unlawful_sexual_contact'
  | 'unlawful_physical_contact'
  | 'sexual_misconduct'
  | 'use_of_restrictive_practice'
  | 'workplace_injury'
  | 'near_miss'
  | 'property_security'
  | 'other';
export type IncidentStatus = 'open' | 'notified' | 'under_review' | 'closed';
export type RiskCategory =
  | 'operational'
  | 'financial'
  | 'compliance'
  | 'whs'
  | 'clinical'
  | 'reputational'
  | 'other';
export type RiskLevel = 'low' | 'medium' | 'high' | 'critical';
export type RiskStatus = 'open' | 'monitoring' | 'mitigated' | 'closed';

export type Profile = {
  id: string;
  organisation_id: string;
  full_name: string;
  email: string;
  role: ProfileRole;
  is_treasurer: boolean;
  handles_risk_compliance: boolean;
  handles_participant_outcomes: boolean;
  is_ceo_escalation_point: boolean;
  phone: string | null;
  active: boolean;
  created_at: string;
  updated_at: string;
};

export type Client = {
  id: string;
  organisation_id: string;
  name: string;
  dob: string | null;
  ndis_number: string | null;
  plan_end_date: string | null;
  support_coordinator: string | null;
  phone: string | null;
  address: string | null;
  emergency_contact: string | null;
  care_plan: string | null;
  routines: string | null;
  communication_preferences: string | null;
  goals: string | null;
  status: ClientStatus;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};

export type Note = {
  id: string;
  organisation_id: string;
  client_id: string;
  author_id: string;
  date: string;
  text: string;
  created_at: string;
  updated_at: string;
};

export type Shift = {
  id: string;
  organisation_id: string;
  client_id: string;
  staff_id: string;
  date: string;
  start_time: string | null;
  end_time: string | null;
  status: ShiftStatus;
  notes: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};

export type Task = {
  id: string;
  organisation_id: string;
  title: string;
  description: string | null;
  due_date: string | null;
  assignee_id: string | null;
  priority: TaskPriority;
  status: TaskStatus;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};

export type Message = {
  id: string;
  organisation_id: string;
  author_id: string;
  date: string;
  text: string;
  created_at: string;
};

export type MessageTag = {
  id: string;
  organisation_id: string;
  message_id: string;
  client_id: string | null;
  profile_id: string | null;
  created_at: string;
};

export type EventVisibility = 'shared' | 'solo';

export type Event = {
  id: string;
  organisation_id: string;
  title: string;
  description: string | null;
  date: string;
  start_time: string | null;
  end_time: string | null;
  visibility: EventVisibility;
  owner_id: string;
  created_at: string;
  updated_at: string;
};

export type EventTag = {
  id: string;
  organisation_id: string;
  event_id: string;
  client_id: string | null;
  profile_id: string | null;
  created_at: string;
};

export type DocumentRow = {
  id: string;
  organisation_id: string;
  title: string;
  category: DocumentCategory;
  status: DocumentStatus;
  client_id: string | null;
  uploader_id: string;
  approver_id: string | null;
  notes: string | null;
  file_path: string | null;
  created_at: string;
  updated_at: string;
};

export type Transaction = {
  id: string;
  organisation_id: string;
  type: TransactionType;
  category: string;
  amount: number;
  date: string;
  description: string | null;
  client_id: string | null;
  staff_id: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};

export type OnboardingRecord = {
  id: string;
  organisation_id: string;
  person_id: string;
  step: OnboardingStep;
  completed: boolean;
  completed_date: string | null;
  expiry_date: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
};

export type ReportableIncident = {
  id: string;
  organisation_id: string;
  domain: IncidentDomain;
  category: IncidentCategory;
  client_id: string | null;
  reported_by: string;
  incident_at: string;
  discovered_at: string;
  description: string;
  immediate_action_taken: string | null;
  is_ndis_reportable: boolean;
  notification_due_at: string | null;
  notified_at: string | null;
  notified_body: string | null;
  status: IncidentStatus;
  outcome: string | null;
  closed_at: string | null;
  created_at: string;
  updated_at: string;
};

export type ConsentScope = 'routines_only' | 'routines_and_comms' | 'full_summary';

export type ShareTokenRow = {
  id: string;
  organisation_id: string;
  client_id: string;
  token: string;
  scope: ConsentScope;
  created_by: string | null;
  created_at: string;
  expires_at: string | null;
  revoked: boolean;
};

export type TaskTag = {
  id: string;
  organisation_id: string;
  task_id: string;
  client_id: string | null;
  profile_id: string | null;
  created_at: string;
};

export type RiskRegisterEntry = {
  id: string;
  organisation_id: string;
  title: string;
  description: string | null;
  category: RiskCategory;
  likelihood: RiskLevel;
  impact: RiskLevel;
  mitigation: string | null;
  owner_id: string | null;
  status: RiskStatus;
  identified_date: string;
  review_date: string | null;
  last_reviewed_at: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};

// --- Specialist plan governance model -------------------------------------

export type Specialty =
  | 'behaviour_support_practitioner'
  | 'gp'
  | 'psychiatrist'
  | 'speech_pathologist'
  | 'dietician'
  | 'physiotherapist'
  | 'occupational_therapist'
  | 'clinical_supervisor'
  | 'other';

export type EngagementStatus = 'active' | 'ended';

export type SpecialistEngagement = {
  id: string;
  organisation_id: string;
  specialist_id: string;
  client_id: string;
  specialty: Specialty;
  start_date: string;
  end_date: string | null;
  status: EngagementStatus;
  referral_notes: string | null;
  authorised_by: string | null;
  created_at: string;
  updated_at: string;
};

export type PlanType = {
  id: string;
  organisation_id: string;
  code: string;
  name: string;
  responsible_specialty: Specialty;
  active: boolean;
  created_at: string;
  updated_at: string;
};

export type SignoffStatus = 'draft' | 'pending_authorisation' | 'authorised' | 'declined' | 'expired';

export type SpecialistPlan = {
  id: string;
  organisation_id: string;
  client_id: string;
  plan_type_id: string;
  operational_summary: string;
  details: Record<string, unknown>;
  status: SignoffStatus;
  authorised_by: string | null;
  authorised_at: string | null;
  expiry_date: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};

export type SpecialistPlanFormulation = {
  id: string;
  specialist_plan_id: string;
  organisation_id: string;
  formulation_detail: string;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};

export type AccessGrantScope = 'specific_plan' | 'plan_type' | 'client_formulation_all';

export type AccessGrant = {
  id: string;
  organisation_id: string;
  grantee_id: string;
  scope_type: AccessGrantScope;
  specialist_plan_id: string | null;
  plan_type_id: string | null;
  client_id: string | null;
  justification: string;
  approved_by: string;
  granted_at: string;
  review_date: string | null;
  expires_at: string | null;
  revoked: boolean;
  revoked_at: string | null;
  revoked_by: string | null;
  created_at: string;
};

export type RiskTierSource = 'suggested' | 'clinical_override';

export type SpecialistPlanRiskRating = {
  id: string;
  organisation_id: string;
  specialist_plan_id: string;
  tier: RiskLevel;
  suggested_tier: RiskLevel | null;
  source: RiskTierSource;
  rationale: string | null;
  incident_window_months: number;
  effective_from: string;
  set_by: string | null;
  created_at: string;
};

export type ReviewCadenceRule = {
  id: string;
  organisation_id: string;
  tier: RiskLevel;
  interval_months: number;
  updated_by: string | null;
  created_at: string;
  updated_at: string;
};

export type ReviewStatus = 'scheduled' | 'held' | 'overdue' | 'cancelled';
export type ReviewOutcome = 'continue_unchanged' | 'reduce' | 'eliminate' | 'escalate';

export type PlanReview = {
  id: string;
  organisation_id: string;
  specialist_plan_id: string;
  client_id: string;
  scheduled_date: string;
  held_date: string | null;
  status: ReviewStatus;
  outcome: ReviewOutcome | null;
  participant_input: string | null;
  resulting_risk_rating_id: string | null;
  next_review_due: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};

export type PlanReviewClinicalNote = {
  id: string;
  review_id: string;
  organisation_id: string;
  clinical_summary: string;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};

export type ReviewParticipantType =
  | 'specialist'
  | 'support_coordinator'
  | 'family'
  | 'advocate'
  | 'service_manager'
  | 'community_member'
  | 'worker_representative'
  | 'participant'
  | 'other';

export type ReviewSegment = 'participant_voice' | 'clinical_discussion' | 'both';

export type ReviewParticipant = {
  id: string;
  organisation_id: string;
  review_id: string;
  participant_type: ReviewParticipantType;
  profile_id: string | null;
  external_name: string | null;
  external_relationship: string | null;
  attended_segment: ReviewSegment;
  notes: string | null;
  created_at: string;
};

export type EscalationSource = 'plan_review' | 'incident' | 'risk_register' | 'other';
export type EscalationStatus = 'raised' | 'groundwork' | 'risk_compliance_review' | 'ceo_reviewed' | 'resolved';

export type Escalation = {
  id: string;
  organisation_id: string;
  client_id: string | null;
  source: EscalationSource;
  source_review_id: string | null;
  source_incident_id: string | null;
  reason: string;
  status: EscalationStatus;
  raised_by: string;
  risk_compliance_owner: string | null;
  participant_outcomes_owner: string | null;
  ceo_id: string | null;
  resolution: string | null;
  resolved_at: string | null;
  created_at: string;
  updated_at: string;
};

export type EscalationUpdate = {
  id: string;
  organisation_id: string;
  escalation_id: string;
  author_id: string;
  stage: EscalationStatus;
  note: string;
  created_at: string;
};

export type DeletableTable =
  | 'clients'
  | 'notes'
  | 'documents'
  | 'transactions'
  | 'reportable_incidents'
  | 'risk_register'
  | 'consent_records'
  | 'specialist_engagements'
  | 'specialist_plans'
  | 'specialist_plan_formulations'
  | 'specialist_plan_risk_ratings'
  | 'plan_reviews'
  | 'plan_review_clinical_notes'
  | 'review_participants'
  | 'escalations'
  | 'escalation_updates'
  | 'complaints_register';

export type DeletionRequestStatus = 'pending' | 'approved' | 'declined';

export type DeletionRequest = {
  id: string;
  organisation_id: string;
  table_name: DeletableTable;
  record_id: string;
  reason: string;
  requested_by: string;
  status: DeletionRequestStatus;
  decided_by: string | null;
  decided_at: string | null;
  decision_note: string | null;
  created_at: string;
};

// Mirrors postgrest-js's GenericTable shape (Row/Insert/Update/Relationships)
// so supabase-js's type inference for insert/update/select resolves
// correctly instead of collapsing to `never`. Relationships is left empty
// (no embedded-resource typing) — this codebase deliberately avoids
// PostgREST embedded selects in favour of separate queries, so no
// relationship metadata is needed. See the file header note on
// regenerating this file from a live project.
type TableDef<Row, Insert, Update = Partial<Insert>> = {
  Row: Row;
  Insert: Insert;
  Update: Update;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      profiles: TableDef<Profile, Partial<Profile> & { id: string }>;
      clients: TableDef<
        Client,
        Partial<Omit<Client, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          name: string;
        }
      >;
      notes: TableDef<
        Note,
        Partial<Omit<Note, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          client_id: string;
          author_id: string;
          text: string;
        }
      >;
      shifts: TableDef<
        Shift,
        Partial<Omit<Shift, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          client_id: string;
          staff_id: string;
          date: string;
        }
      >;
      tasks: TableDef<
        Task,
        Partial<Omit<Task, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          title: string;
        }
      >;
      share_tokens: TableDef<
        ShareTokenRow,
        Partial<Omit<ShareTokenRow, 'id' | 'organisation_id' | 'created_at' | 'token'>> & {
          client_id: string;
        }
      >;
      task_tags: TableDef<
        TaskTag,
        Partial<Omit<TaskTag, 'id' | 'organisation_id' | 'created_at'>> & { task_id: string }
      >;
      messages: TableDef<
        Message,
        Partial<Omit<Message, 'id' | 'organisation_id' | 'created_at'>> & {
          author_id: string;
          text: string;
        }
      >;
      message_tags: TableDef<
        MessageTag,
        Partial<Omit<MessageTag, 'id' | 'organisation_id' | 'created_at'>> & { message_id: string }
      >;
      events: TableDef<
        Event,
        Partial<Omit<Event, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          title: string;
          date: string;
          owner_id: string;
        }
      >;
      event_tags: TableDef<
        EventTag,
        Partial<Omit<EventTag, 'id' | 'organisation_id' | 'created_at'>> & { event_id: string }
      >;
      documents: TableDef<
        DocumentRow,
        Partial<Omit<DocumentRow, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          title: string;
          category: DocumentCategory;
          uploader_id: string;
        }
      >;
      transactions: TableDef<
        Transaction,
        Partial<Omit<Transaction, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          type: TransactionType;
          category: string;
          amount: number;
        }
      >;
      onboarding_records: TableDef<
        OnboardingRecord,
        Partial<Omit<OnboardingRecord, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          person_id: string;
          step: OnboardingStep;
        }
      >;
      reportable_incidents: TableDef<
        ReportableIncident,
        Partial<
          Omit<ReportableIncident, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>
        > & {
          category: IncidentCategory;
          reported_by: string;
          incident_at: string;
          description: string;
        }
      >;
      risk_register: TableDef<
        RiskRegisterEntry,
        Partial<Omit<RiskRegisterEntry, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          title: string;
          category: RiskCategory;
          likelihood: RiskLevel;
          impact: RiskLevel;
        }
      >;
      specialist_engagements: TableDef<
        SpecialistEngagement,
        Partial<Omit<SpecialistEngagement, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          specialist_id: string;
          client_id: string;
          specialty: Specialty;
        }
      >;
      plan_types: TableDef<
        PlanType,
        Partial<Omit<PlanType, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          code: string;
          name: string;
          responsible_specialty: Specialty;
        }
      >;
      specialist_plans: TableDef<
        SpecialistPlan,
        Partial<Omit<SpecialistPlan, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          client_id: string;
          plan_type_id: string;
          operational_summary: string;
        }
      >;
      specialist_plan_formulations: TableDef<
        SpecialistPlanFormulation,
        Partial<Omit<SpecialistPlanFormulation, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          specialist_plan_id: string;
          formulation_detail: string;
        }
      >;
      access_grants: TableDef<
        AccessGrant,
        Partial<Omit<AccessGrant, 'id' | 'organisation_id' | 'created_at' | 'granted_at'>> & {
          grantee_id: string;
          scope_type: AccessGrantScope;
          justification: string;
          approved_by: string;
        }
      >;
      specialist_plan_risk_ratings: TableDef<
        SpecialistPlanRiskRating,
        Partial<Omit<SpecialistPlanRiskRating, 'id' | 'organisation_id' | 'created_at'>> & {
          specialist_plan_id: string;
          tier: RiskLevel;
        }
      >;
      review_cadence_rules: TableDef<
        ReviewCadenceRule,
        Partial<Omit<ReviewCadenceRule, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          tier: RiskLevel;
          interval_months: number;
        }
      >;
      plan_reviews: TableDef<
        PlanReview,
        Partial<Omit<PlanReview, 'id' | 'organisation_id' | 'client_id' | 'created_at' | 'updated_at'>> & {
          specialist_plan_id: string;
          scheduled_date: string;
        }
      >;
      plan_review_clinical_notes: TableDef<
        PlanReviewClinicalNote,
        Partial<Omit<PlanReviewClinicalNote, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          review_id: string;
          clinical_summary: string;
        }
      >;
      review_participants: TableDef<
        ReviewParticipant,
        Partial<Omit<ReviewParticipant, 'id' | 'organisation_id' | 'created_at'>> & {
          review_id: string;
          participant_type: ReviewParticipantType;
        }
      >;
      escalations: TableDef<
        Escalation,
        Partial<Omit<Escalation, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          reason: string;
          raised_by: string;
        }
      >;
      escalation_updates: TableDef<
        EscalationUpdate,
        Partial<Omit<EscalationUpdate, 'id' | 'organisation_id' | 'created_at'>> & {
          escalation_id: string;
          author_id: string;
          stage: EscalationStatus;
          note: string;
        }
      >;
      deletion_requests: TableDef<
        DeletionRequest,
        Partial<Omit<DeletionRequest, 'id' | 'organisation_id' | 'created_at'>> & {
          table_name: DeletableTable;
          record_id: string;
          reason: string;
          requested_by: string;
        }
      >;
    };
    Views: Record<string, never>;
    Functions: {
      get_coordinated_summary: {
        Args: { p_token: string };
        Returns: {
          name: string;
          routines: string | null;
          communication_preferences?: string | null;
          goals?: string | null;
          care_plan?: string | null;
        } | null;
      };
      execute_approved_deletion: {
        Args: { request_id: string };
        Returns: undefined;
      };
    };
  };
};
