// Hand-written types mirroring supabase/migrations/*.sql.
//
// These are NOT generated by `supabase gen types` (no live project is
// linked yet). Once a real Supabase project exists, regenerate with:
//   supabase gen types typescript --project-id <ref> > src/types/database.ts
// and reconcile any drift against this file.
//
// IMPORTANT: every Row/Insert/Update shape below is declared with `type`,
// not `interface`. This is not a style choice — TypeScript's structural
// check for "does this satisfy Record<string, unknown>" (which
// supabase-js's GenericTable constraint relies on) treats `interface`
// declarations as NOT satisfying an index signature, even though a
// structurally identical `type` alias does. Using `interface` here
// silently collapses every table's Insert/Update/Row generics to `never`
// with no error pointing at the cause — see the PR description for the
// full diagnosis. Keep these as `type`.

export type ProfileRole = 'admin' | 'care_advocacy' | 'committee' | 'contractor' | 'specialist';
export type ClientStatus = 'active' | 'inactive';
export type ShiftStatus = 'scheduled' | 'completed' | 'cancelled';
export type TaskPriority = 'low' | 'medium' | 'high';
export type TaskStatus = 'todo' | 'in_progress' | 'done';
export type DocumentCategory =
  | 'care_plan'
  | 'bsp_risk_plan'
  | 'consent_form'
  | 'service_agreement'
  | 'policy'
  | 'correspondence'
  | 'other';
export type DocumentStatus = 'draft' | 'pending_approval' | 'approved';
export type TransactionType = 'income' | 'expense';
export type OnboardingStep =
  | 'wwcc'
  | 'ndis_screening'
  | 'orientation'
  | 'code_of_conduct'
  | 'referees'
  | 'induction';
export type IncidentDomain = 'ndis_reportable' | 'whs' | 'security' | 'other';
export type IncidentCategory =
  | 'death'
  | 'serious_injury'
  | 'abuse'
  | 'neglect'
  | 'unlawful_sexual_contact'
  | 'unlawful_physical_contact'
  | 'sexual_misconduct'
  | 'use_of_restrictive_practice'
  | 'workplace_injury'
  | 'near_miss'
  | 'property_security'
  | 'other';
export type IncidentStatus = 'open' | 'notified' | 'under_review' | 'closed';
export type RiskCategory =
  | 'operational'
  | 'financial'
  | 'compliance'
  | 'whs'
  | 'clinical'
  | 'reputational'
  | 'other';
export type RiskLevel = 'low' | 'medium' | 'high' | 'critical';
export type RiskStatus = 'open' | 'monitoring' | 'mitigated' | 'closed';

export type Profile = {
  id: string;
  organisation_id: string;
  full_name: string;
  email: string;
  role: ProfileRole;
  is_treasurer: boolean;
  phone: string | null;
  active: boolean;
  created_at: string;
  updated_at: string;
};

export type Client = {
  id: string;
  organisation_id: string;
  name: string;
  dob: string | null;
  ndis_number: string | null;
  plan_end_date: string | null;
  support_coordinator: string | null;
  phone: string | null;
  address: string | null;
  emergency_contact: string | null;
  care_plan: string | null;
  routines: string | null;
  communication_preferences: string | null;
  goals: string | null;
  status: ClientStatus;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};

export type Note = {
  id: string;
  organisation_id: string;
  client_id: string;
  author_id: string;
  date: string;
  text: string;
  created_at: string;
  updated_at: string;
};

export type Shift = {
  id: string;
  organisation_id: string;
  client_id: string;
  staff_id: string;
  date: string;
  start_time: string | null;
  end_time: string | null;
  status: ShiftStatus;
  notes: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};

export type Task = {
  id: string;
  organisation_id: string;
  title: string;
  description: string | null;
  due_date: string | null;
  assignee_id: string | null;
  priority: TaskPriority;
  status: TaskStatus;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};

export type DocumentRow = {
  id: string;
  organisation_id: string;
  title: string;
  category: DocumentCategory;
  status: DocumentStatus;
  client_id: string | null;
  uploader_id: string;
  approver_id: string | null;
  notes: string | null;
  file_path: string | null;
  created_at: string;
  updated_at: string;
};

export type Transaction = {
  id: string;
  organisation_id: string;
  type: TransactionType;
  category: string;
  amount: number;
  date: string;
  description: string | null;
  client_id: string | null;
  staff_id: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};

export type OnboardingRecord = {
  id: string;
  organisation_id: string;
  person_id: string;
  step: OnboardingStep;
  completed: boolean;
  completed_date: string | null;
  expiry_date: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
};

export type ReportableIncident = {
  id: string;
  organisation_id: string;
  domain: IncidentDomain;
  category: IncidentCategory;
  client_id: string | null;
  reported_by: string;
  incident_at: string;
  discovered_at: string;
  description: string;
  immediate_action_taken: string | null;
  is_ndis_reportable: boolean;
  notification_due_at: string | null;
  notified_at: string | null;
  notified_body: string | null;
  status: IncidentStatus;
  outcome: string | null;
  closed_at: string | null;
  created_at: string;
  updated_at: string;
};

export type ConsentScope = 'routines_only' | 'routines_and_comms' | 'full_summary';

export type ShareTokenRow = {
  id: string;
  organisation_id: string;
  client_id: string;
  token: string;
  scope: ConsentScope;
  created_by: string | null;
  created_at: string;
  expires_at: string | null;
  revoked: boolean;
};

export type TaskTag = {
  id: string;
  organisation_id: string;
  task_id: string;
  client_id: string | null;
  profile_id: string | null;
  created_at: string;
};

export type RiskRegisterEntry = {
  id: string;
  organisation_id: string;
  title: string;
  description: string | null;
  category: RiskCategory;
  likelihood: RiskLevel;
  impact: RiskLevel;
  mitigation: string | null;
  owner_id: string | null;
  status: RiskStatus;
  identified_date: string;
  review_date: string | null;
  last_reviewed_at: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};

// Mirrors postgrest-js's GenericTable shape (Row/Insert/Update/Relationships)
// so supabase-js's type inference for insert/update/select resolves
// correctly instead of collapsing to `never`. Relationships is left empty
// (no embedded-resource typing) — this codebase deliberately avoids
// PostgREST embedded selects in favour of separate queries, so no
// relationship metadata is needed. See the file header note on
// regenerating this file from a live project.
type TableDef<Row, Insert, Update = Partial<Insert>> = {
  Row: Row;
  Insert: Insert;
  Update: Update;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      profiles: TableDef<Profile, Partial<Profile> & { id: string }>;
      clients: TableDef<
        Client,
        Partial<Omit<Client, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          name: string;
        }
      >;
      notes: TableDef<
        Note,
        Partial<Omit<Note, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          client_id: string;
          author_id: string;
          text: string;
        }
      >;
      shifts: TableDef<
        Shift,
        Partial<Omit<Shift, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          client_id: string;
          staff_id: string;
          date: string;
        }
      >;
      tasks: TableDef<
        Task,
        Partial<Omit<Task, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          title: string;
        }
      >;
      share_tokens: TableDef<
        ShareTokenRow,
        Partial<Omit<ShareTokenRow, 'id' | 'organisation_id' | 'created_at' | 'token'>> & {
          client_id: string;
        }
      >;
      task_tags: TableDef<
        TaskTag,
        Partial<Omit<TaskTag, 'id' | 'organisation_id' | 'created_at'>> & { task_id: string }
      >;
      documents: TableDef<
        DocumentRow,
        Partial<Omit<DocumentRow, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          title: string;
          category: DocumentCategory;
          uploader_id: string;
        }
      >;
      transactions: TableDef<
        Transaction,
        Partial<Omit<Transaction, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          type: TransactionType;
          category: string;
          amount: number;
        }
      >;
      onboarding_records: TableDef<
        OnboardingRecord,
        Partial<Omit<OnboardingRecord, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          person_id: string;
          step: OnboardingStep;
        }
      >;
      reportable_incidents: TableDef<
        ReportableIncident,
        Partial<
          Omit<ReportableIncident, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>
        > & {
          category: IncidentCategory;
          reported_by: string;
          incident_at: string;
          description: string;
        }
      >;
      risk_register: TableDef<
        RiskRegisterEntry,
        Partial<Omit<RiskRegisterEntry, 'id' | 'organisation_id' | 'created_at' | 'updated_at'>> & {
          title: string;
          category: RiskCategory;
          likelihood: RiskLevel;
          impact: RiskLevel;
        }
      >;
    };
    Views: Record<string, never>;
    Functions: {
      get_coordinated_summary: {
        Args: { p_token: string };
        Returns: {
          name: string;
          routines: string | null;
          communication_preferences?: string | null;
          goals?: string | null;
          care_plan?: string | null;
        } | null;
      };
    };
  };
};
